In [1]:

import numpy as np
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [2]:
#Iterating 2-D Arrays
#In a 2-D array it will go through all the rows.


arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [4]:
#Iterating 3-D Arrays
#In a 3-D array it will go through all the 2-D arrays.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [5]:
#Iterating With Different Step Size
#We can use filtering and followed by iteration.

#Example
#Iterate through every scalar element of the 2D array skipping 1 element:



arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


#Joining NumPy Arrays

In [8]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [10]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
#Join two 2-D arrays along rows (axis=1):

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [12]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

##The example above will return a tuple: (array([3, 5, 6],)

##Which means that the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [13]:
#Find the indexes where the values are even:


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [14]:
#Find the indexes where the values are odd:


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [15]:
#Search From the Right Side
#By default the left most index is returned, but we can give side='right' to return the right most index instead.

#Example
#Find the indexes where the value 7 should be inserted, starting from the right:



arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [29]:
#Sorting Arrays
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


array([0, 1, 2, 3])

In [21]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
arr.sort

['apple' 'banana' 'cherry']


In [22]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [23]:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
