# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
# Python program to demonstrate a need of NumPy
 
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]
 


In [2]:
# Multiplying both lists directly would give an error.
print(list1*list2)

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Convert list1 into a NumPy array
a1 = np.array(list1)
 
# Convert list2 into a NumPy array
a2 = np.array(list2)
 
print(a1*a2)

[10 18 24 28 30 30]


In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\mrspider\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\mrspider\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [11]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [12]:
arr +arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [13]:
arr +arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
arr /arr

array([[1., 1., 1.],
       [1., 1., 1.]])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [18]:
#Taking Square Roots
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [19]:
#Calcualting exponential (e^)
np.exp(arr)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [20]:
np.max(arr) #same as arr.max()

6

In [21]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [22]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

# Great Job!

That's all we need to know for now!