# Numpy

In [1]:
import numpy as np 

In [2]:
#create an array  by directly converting a list or list of list:
list = [1,2,3,11,5]
list

[1, 2, 3, 11, 5]

In [3]:
np.array

<function numpy.array>

In [4]:
y=np.array(list)

In [5]:
y.std()

3.5552777669262356

In [7]:
y.sort()
y

array([ 1,  2,  3,  5, 11])

In [9]:
y.max()

11

In [10]:
y.min()

1

In [11]:
y.mean()

4.4

In [12]:
matrix = [[1,2,3,],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,8)  #same as a range function

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
np.arange(5,9)

array([5, 6, 7, 8])

In [17]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [18]:
a = np.array([[1,2,3],[4,5,6]])  #Number of Rows and Col
print(a.shape)

(2, 3)


In [20]:
print(a.size)

6


In [21]:
a.dtype.name

'int32'

In [22]:
a.itemsize #size of each elements/item

4

In [23]:
np.zeros(5)  #generate array of zeros and ones

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.ones(3)*5

array([5., 5., 5.])

In [29]:
np.ones((5,5))*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [30]:
#LinSpacing

# step length = upper limit - lower limit /(#point - 1)
#h = 4-2/3-1 = 2/2 = 1 ---- h=1

In [31]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [32]:
np.linspace(1,21,5)

array([ 1.,  6., 11., 16., 21.])

In [33]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.linspace(0,15,5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [35]:
np.linspace(0,10,50) # 50 Equdistant points will br generated

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [37]:
np.eye(4)  # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [39]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [40]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [44]:
#TO GENERATE THE RANDOM NUMBER 
#Random values in a given shape.
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

np.random.rand(2)

array([0.29165424, 0.98348791])

In [45]:
np.random.rand(5,5)

array([[0.13398394, 0.8569659 , 0.42224696, 0.17915534, 0.19143058],
       [0.18342763, 0.63802511, 0.73962294, 0.47481457, 0.37191646],
       [0.41660806, 0.6721396 , 0.9494422 , 0.58984039, 0.67274518],
       [0.72431371, 0.09356776, 0.01315733, 0.56797236, 0.29106715],
       [0.5631613 , 0.99396112, 0.84075208, 0.71749507, 0.5413    ]])

In [46]:
#Return a sample (or samples) from the “standard normal” distribution.

#If positive, int_like or int-convertible arguments are provided, randn generates an array of shape (d0, d1, ..., dn),
#filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1
#(if any of the d_i are floats, they are first converted to integers by truncation).
#A single float randomly sampled from the distribution is returned if no argument is provided.

#This is a convenience function. If you want an interface that takes a tuple as the first argument,
#use numpy.random.standard_normal instead.

np.random.randn(2)

array([ 1.48777408, -0.22163188])

In [47]:
np.random.randn(5,5)

array([[ 0.16337586,  0.48069109, -0.67657117, -1.15100345, -1.48813945],
       [-0.06353351, -0.71209133,  0.25814068, -1.74947855,  0.56162514],
       [ 0.98584451, -0.88500483,  0.49399743, -0.73675164,  1.59730081],
       [-0.49235975, -0.74871046, -1.29133738, -0.86362987,  1.38441144],
       [-0.65745381,  0.58509093,  0.19473412, -1.19529492, -1.48873568]])

In [48]:
# randint --- generete random integer from low (inclusive) to high (inclusive)

np.random.randint(2)

1

In [49]:
np.random.randint(1,100,5)

array([59, 11, 82, 82, 37])

In [50]:
np.random.randint(1,100,(5,5))

array([[88, 62, 55, 62,  8],
       [24, 99, 47, 64, 32],
       [89, 47, 65, 23, 50],
       [18, 56, 60, 82, 14],
       [89, 64, 70, 87, 71]])

In [ ]:
# Array attributes and methods

In [51]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
ranarr = np.random.randint(0,50,10)
ranarr

array([34,  1, 45,  7, 47, 37, 33, 41, 21,  9])

In [53]:
# returns an array containing the same data with a new shape

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
ranarr

array([34,  1, 45,  7, 47, 37, 33, 41, 21,  9])

In [57]:
ranarr.max() # max value

47

In [58]:
ranarr.argmax() #element index

4

In [59]:
ranarr.min() #min value

1

In [60]:
ranarr.argmin() # element index

1