Q.1 Write a program using list comprehension to find primes in range 2 to 100.

In [4]:
primes = [num for num in range(2,100) if 0 not in [num%i for i in range(2,int(num/2)+1)]]
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


Q.2 Write a function to reverse a string.

In [1]:
def rev_string(x):
    return x[::-1]
string = rev_string("Please . dont . unplug . the . LAN . from . the . port")
print(string)

trop . eht . morf . NAL . eht . gulpnu . tnod . esaelP


Q.3
Write a program to extract the words from the given list which have their first character in uppercase.

In [6]:
Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']

output = []
for i in Days:
    if (i[0].isupper() == True):
        output.append(i)
print("Output:",output)

Output: ['Monday', 'Sunday', 'Saturday']


Q.4
Write a program to extract the year part from the dates in the given list.

In [7]:
Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']
count = 0
count1 = 0
while count1<len(Batch):
    while count<len(Batch):
        x = Batch[count].index('-',1)
        y = Batch[count].index('-',x+1)
        print(Batch[count][y+1:])
        count+=1
        count1+=1

1997
2011
1993
2020


Q.5
Write a program swap the keys to values and values to keys of the given dictionary.

In [8]:
Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}
print(Module)
swap = {value:key for key, value in Module.items()}
print(swap)

{'Data Science': 1, 'Machine Learning': 2, 'SQL': 3, 'Big Data': 4}
{1: 'Data Science', 2: 'Machine Learning', 3: 'SQL', 4: 'Big Data'}


Q6 Write a program to calculate the cumulative average of the given list using accumulate() and lambda function.

In [9]:
from functools import reduce

def Average(l): 
    avg = reduce(lambda x, y: x + y, l) / len(l)
    return avg
  
list = [5,2,1,4,6] 
average = Average(list) 
  
print("Average of list is", average)

Average of list is 3.6


Q.7 Write a program to count the number of elements in the string (given by the user) that are not present in the 'my_string'. Do not count the white spaces.
Use Recursion my_string = 'Data Science'

In [18]:
def string_length(my_string) : 
    count = 0
    for x in my_string:
        if x !=" ":
            count = 1+count
        
    return count
    
my_string = 'Data Science'
print (string_length(my_string))

11


Q.8
Define a function to check whether a number is in a range (1000,10000) or not.

In [10]:
def test_range(n):
    if n in range(1000,10000):
        print( " %s is in the range"%str(n))
    else :
        print("The number is outside the given range.")
test_range(5)

The number is outside the given range.


Q.9
Write a program to print pascal triangle upto 6 steps
(using list).

In [12]:
n=int(input("Enter number of rows: "))
a=[]
for i in range(n):
    a.append([])
    a[i].append(1)
    for j in range(1,i):
        a[i].append(a[i-1][j-1]+a[i-1][j])
    if(n!=0):
        a[i].append(1)
for i in range(n):
    print("   "*(n-i),end=" ",sep=" ")
    for j in range(0,i+1):
        print('{0:6}'.format(a[i][j]),end=" ",sep=" ")
    print()

Enter number of rows: 5
                     1 
                  1      1 
               1      2      1 
            1      3      3      1 
         1      4      6      4      1 


Q.10 Write a program to calculate the sum of all elements in
the list.

In [13]:
total = 0
test_score = [10, 32, 23, 14, 25]
for ele in range(0, len(test_score)):
    total = total + test_score[ele]
print("Sum of all elements in given list: ", total)


Sum of all elements in given list:  104


Q.11
Find the minimum value along each of the rows.
Create a 2D Numpy array from list of lists

In [14]:
import numpy as np

Score = np.array([[210, 402, 383],[140, 375, 106],[140, 125, 217],[292, 240, 295]])
print(Score)
Score.min(axis=1)

[[210 402 383]
 [140 375 106]
 [140 125 217]
 [292 240 295]]


array([210, 106, 125, 240])

Q.12
Replace all even numbers in the array with -1.
Use the array given below

In [15]:
num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

output = []
for i in num_array:
    if (i%2 == 0):
        output.append(-1)
    else:
        output.append(i)

print(output)

[-1, 21, -1, 13, -1, 45, -1, -1, -1, -1, 65, -1, -1]
